version: "3"
services:
  reactblog:
    build:
      context: .
    ports:
      - "3000:3000"
    environment: 
      - REACT_APP_API_URL=${REACT_APP_API_URL:-localhost:8000}
    volumes:
      - ./reactblog:/reactblog
      - /reactblog/node_modules
    command: >
      sh -c "npm start"
